// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp8eaA1wO-H9nt-WqquBwavtabe25G2_w',
    appId: '1:791903257273:web:12007b44e6ce46ba2e9168',
    messagingSenderId: '791903257273',
    projectId: 'sis-patrullaje-cusco',
    authDomain: 'sis-patrullaje-cusco.firebaseapp.com',
    storageBucket: 'sis-patrullaje-cusco.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR5tN7Pt3_T0kIZSIDULEFlBk_491l6ok',
    appId: '1:791903257273:android:a2dc93e87996547b2e9168',
    messagingSenderId: '791903257273',
    projectId: 'sis-patrullaje-cusco',
    storageBucket: 'sis-patrullaje-cusco.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-20t8W3TM5aOo1FbiSMImWIhpwynqZwk',
    appId: '1:791903257273:ios:6ba9f1a6019d9bf42e9168',
    messagingSenderId: '791903257273',
    projectId: 'sis-patrullaje-cusco',
    storageBucket: 'sis-patrullaje-cusco.firebasestorage.app',
    iosBundleId: 'com.example.sisPatrullajeCusco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-20t8W3TM5aOo1FbiSMImWIhpwynqZwk',
    appId: '1:791903257273:ios:6ba9f1a6019d9bf42e9168',
    messagingSenderId: '791903257273',
    projectId: 'sis-patrullaje-cusco',
    storageBucket: 'sis-patrullaje-cusco.firebasestorage.app',
    iosBundleId: 'com.example.sisPatrullajeCusco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp8eaA1wO-H9nt-WqquBwavtabe25G2_w',
    appId: '1:791903257273:web:1e1868e2e793fd442e9168',
    messagingSenderId: '791903257273',
    projectId: 'sis-patrullaje-cusco',
    authDomain: 'sis-patrullaje-cusco.firebaseapp.com',
    storageBucket: 'sis-patrullaje-cusco.firebasestorage.app',
  );
}
